### ISSUE TITLE
when you make a move, you can't undo it.

### ISSUE THREAD

**Issue by Aw0d** [rivafarabi/voicemeeter-control#1]
When, for example, I mute my microphone by pressing the button I have configured, by pressing the same button again, I cannot mute my microphone. How can I make it work?

**Comment by terenc3** [comment]
I think you want to toggle the mute button. Since this is not working in the original I've created a fork and implemented this. https://github.com/terenc3/voicemeeter-control/

**Comment by astronaut954** [comment]
> I think you want to toggle the mute button. Since this is not working in the original I've created a fork and implemented this. https://github.com/terenc3/voicemeeter-control/

Hi @terenc3, for some reason your fork project won't install. I've cloned into the right directory and used the right commands but I get just a lot of errors. Here is the log:

[2021-05-04T05_19_17_016Z-debug.log](https://github.com/rivafarabi/voicemeeter-control/files/6419129/2021-05-04T05_19_17_016Z-debug.log)

**Comment by terenc3** [comment]
@astronaut954 the important part of you error message is:

3647 warn notsup Unsupported engine for voicemeeter-connector@0.6.2: wanted: {"node":"^8 || ^10"} (current: {"node":"14.16.1","npm":"6.14.12"})
3648 warn notsup Not compatible with your version of node/npm: voicemeeter-connector@0.6.2

See https://github.com/rivafarabi/voicemeeter-control/pull/8#issuecomment-863809629 for a downloadable package
