### ISSUE TITLE
Voicemeeter-Control Extension not working

### ISSUE THREAD

**Issue by lastfight88** [rivafarabi/voicemeeter-control#12]
"Voicemeeter Control" Extension not working in Deckboard version 2.0.5

**Comment by AIO-Software-tech** [comment]
Please fix this i use it so much

**Comment by rivafarabi** [comment]
Which version of voicemeeter are you using?

**Comment by GhostOceanborn** [comment]
I have the same problem after the deckboard version 2.0.5 update. I use voicemmeter potato 3.0.2.2. And I never had any problems before.

**Comment by Dking07-zz** [comment]
same problem here

**Comment by lastfight88** [comment]
Voicemmeter Potato 3.0.2.2  .. i try to install the Extension and then restart deckboard .. the Extension is not install after the restart.  sorry my bad english.

**Comment by rivafarabi** [comment]
I've just released the latest version ([v1.3.0](https://github.com/rivafarabi/voicemeeter-control/releases/tag/v1.3.0)) to fix the compatibility issue with Deckboard v2.0.5

**Comment by lastfight88** [comment]
thanks soooo much :*

**Comment by GhostOceanborn** [comment]
Working perfectly now. Thanks.

**Comment by rivafarabi** [comment]
Great! I'm closing this issue now.
