### ISSUE TITLE
[BUG] Voicemeeter plugin problem

### ISSUE THREAD

**Issue by pxlfl4me** [rivafarabi/voicemeeter-control#16]
I tried and actually now I find it, the only thing is that I'm encountering a problem, if I use the toggle strip parameter option, the parameter at the desired index if active is deactivated, but if I click it a second time it doesn't reactivate, would you know give me a way to solve?

_Originally posted by @pxlfl4me in https://github.com/rivafarabi/deckboard/issues/1105#issuecomment-2169850066_

**Comment by rivafarabi** [comment]
Fixed in [v1.5.1](https://github.com/rivafarabi/voicemeeter-control/releases/tag/v1.5.1)
