### ISSUE TITLE
Can't select any options

### ISSUE THREAD

**Issue by LilJur** [rivafarabi/voicemeeter-control#5]
So I just tried using this.
When I select "Set Strip Parameter", it doesn't show me any options. I can't select any strips or parameters.
What am I doing wrong?

**Comment by rivafarabi** [comment]
Thanks for the info. For the time being, please use [v1.0.0](https://github.com/rivafarabi/voicemeeter-control/releases/tag/v1.0.0) until next release.

**Comment by chrisbadley** [comment]
> Thanks for the info. For the time being, please use [v1.0.0](https://github.com/rivafarabi/voicemeeter-control/releases/tag/v1.0.0) until next release.

Any idea when the next release will be?

**Comment by rivafarabi** [comment]
The extension has been updated to version 1.2.0
This update include the fix for disappearing dropdowns in version 1.1.0
